[build]
installCommand = "composer install --optimize-autoloader --no-scripts --no-interaction"

[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "php84Packages.fileinfo", "php84Packages.gd", "php84Packages.sqlite"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"